### ISSUE TITLE
Turn this into a singular module

### ISSUE THREAD

**Issue by Royalgamer06** [irqize/node-steam-market-sell-bot#1]
Right now, you use 2 modules (steamBot.js and apiRequests.js) for your client code (app.js). It would be nice to turn it into 1 package/module (e.g. node-steam-market) and publish it to npmjs registry. Also, some documentation on the methods would be nice. Finally, allow us to pass instances of steam-user, steamcommunity, etc ourselves, as we are most likely using these in our client code too for other stuff and this way we can avoid logging into both modules multiple times.

**Comment by irqize** [comment]
Hey, I might just have something for you [https://github.com/irqize/node-steam-market-sell](node-steam-market-sell) :)
